org.gradle.jvmargs=-Xmx1G

minecraft_version=1.21.1
parchment_release=2024.11.17
fabric_version=0.16.10
neoforge_version=21.1.119

# Fabric API
fabric_api_version=0.115.1+1.21.1
jsonem_version=0.3+1.21
controlify_version=2.0.1+1.21

mod_version = 0.5.1
maven_group = io.github.foundationgames
archives_base_name = automobility
