modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="automobility"
version="${version}"
displayName="Automobility"
logoFile="automobility.png"
authors="FoundationGames, Toastworth" #optional
description='''
Vehicles and whatnot
'''

[[mixins]]
config = "automobility.mixins.json"

[[mixins]]
config = "automobility_neoforge.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.automobility]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.automobility]]
modId="minecraft"
type="required"
versionRange="[1.21,1.21.1]"
ordering="NONE"
side="BOTH"
